pub use multiple_of_eight_check::{generate_multiple_of_eight_bits_check, generate_multiple_of_eight_run_check};
pub use variant_in_range_check::{generate_variant_in_range_check, generate_variant_in_range_run_check};

mod multiple_of_eight_check;

mod variant_in_range_check;