name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust Test ${{matrix.project}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         project: [builder, debug, seq, sorted, bitfield]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{matrix.project}}
        run: cargo test --verbose
        working-directory: ${{matrix.project}}
      
      
      
      
      
      
      
